meca:
  mecanum_encoder_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    joints:
      - encoder_left_forward_joint
      - encoder_left_back_joint
      - encoder_right_back_joint
      - encoder_right_forward_joint
